openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Jobs Triggers
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/jobs/{jobId}/triggers:
    get:
      tags:
        - Job - Trigger
      summary: Get all the Jobs Triggers
      operationId: jobTriggerList
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../job/job.yaml#/components/parameters/jobId'
        - $ref: '../openapi.yaml#/components/parameters/limit'
        - $ref: '../openapi.yaml#/components/parameters/offset'
      responses:
        200:
          description: The list of the Jobs available in the Scope
          content:
            application/json:
              schema:
                $ref: './jobTrigger.yaml#/components/schemas/jobTriggerListResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    post:
      tags:
        - Job - Trigger
      summary: Create a new Job Trigger
      operationId: jobTriggerCreate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      requestBody:
        description: An object containing the properties for the new Job Trigger to be created
        content:
          application/json:
            schema:
              $ref: './jobTrigger.yaml#/components/schemas/jobTriggerCreator'
        required: true
      responses:
        201:
          description: The Job Trigger that has just been created
          content:
            application/json:
              schema:
                $ref: '../job/job.yaml#/components/schemas/job'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    delete:
      tags:
        - Job - Trigger
      summary: Delete a single Job Trigger
      operationId: jobTriggerDelete
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../job/job.yaml#/components/parameters/jobId'
        - $ref: './jobTrigger.yaml#/components/parameters/triggerId'
      responses:
        204:
          description: The Job Trigger has been deleted
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
