language: java

jdk:
- openjdk8

sudo: false
dist: xenial

# The cache is stored per-branch

cache:
  directories:
  - $HOME/.m2

before_script:
  - export BUILD_OPTS=""
  - export CONFIG_OVERRIDES="-Dcommons.db.schema=kapuadb -Dcommons.settings.hotswap=true  -Dbroker.host=localhost"
  - export MAVEN_OPTS="-Xmx1024m"
  - hash -r

install: true

jobs:
  include:
  - stage: build
    script:
    - ./travis.sh mvn -f external/pom.xml install
    - ./travis.sh mvn ${BUILD_OPTS} -DskipTests clean install
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @default"  verify
  #   - bash <(curl -s https://codecov.io/bash)
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @brokerAcl" verify
  #   - bash <(curl -s https://codecov.io/bash)
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @tag" verify
  #   - bash <(curl -s https://codecov.io/bash)
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @broker" verify
  #   - bash <(curl -s https://codecov.io/bash)
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @device" verify
  #   - bash <(curl -s https://codecov.io/bash)
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @connection" verify
  #   - bash <(curl -s https://codecov.io/bash)
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @datastore" verify
  #   - bash <(curl -s https://codecov.io/bash)
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @user" verify
  #   - bash <(curl -s https://codecov.io/bash)
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @security" verify
  #   - bash <(curl -s https://codecov.io/bash)
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobs" verify
  #   - bash <(curl -s https://codecov.io/bash)
  # - stage: test
  #   script:
  #   - ./travis.sh mvn ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='org.eclipse.kapua.qa.markers.junit.JUnitTests' verify
  #   - bash <(curl -s https://codecov.io/bash)
  - stage: test
    script:
    - mvn -DskipTests -f service/api/pom.xml -Ddebug=true -Pjavadoc install javadoc:jar
